{
 "title": "Clinus docker exporter ",
 "tags": [
  "docker",
  "victoriametrics"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "docker_container_cpu_usage", "legendFormat": "{{container_name}}" }
   ]
  },
  {
   "title": "Memory Usage (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "docker_container_memory_usage", "legendFormat": "{{container_name}}" }
   ]
  },
  {
   "title": "Network RX (Bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(docker_container_network_rx[1m])",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Network TX (Bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(docker_container_network_tx[1m])",
     "legendFormat": "{{container_name}}"
    }
   ]
  }
 ]
}